### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by duncaneddy** [sisl/SatelliteDynamics.jl#4]
These are currently features lacking from SatelliteDynamics, but those I would
be interested in adding in the future.

If there is increased demand for certain features over others I would welcome feedback for prioritization. Additionally, if there are features recommendations missing from the list below please feel free to add them.

Future feature development:
- [ ] Add support for control inputs to dynamics propagation
    - [ ] Continuous maneuvering
    - [ ] Impulsive maneuvering
    - [ ] Propagator support for defined control laws
- [ ] Relative Orbital Elements (ROE)
    - [ ] Calculation from absolute orbital elements
    - [ ] Conversion between RTN and ROE formulations
- [ ] Improved numerical integrator support
    - [ ] Variable-Order Variable-Step Shampine Gordon Integrator
    - [ ] Higher-order Runge-Kutta Methods
    - [ ] Return Julia DifferentialEquations support
- [ ] Additional atmospheric models
    - [ ] JB 2008
    - [ ] DTM 2013
- [ ] Add estimator support
- [ ] Add Attitude Dynamics Support
    - [ ] Euler Equation propagation
    - [ ] Gravity Gradient support
    - [ ] Solar Radiation Pressure
    - [ ] Drag Model
    - [ ] Actuator models (reaction wheels, torque rods, thrusters)
- [ ] Earth Magnetic Field Models
- [ ] Non-Earth Reference Frames
- [ ] Non-Earth Gravity Field Models
- [ ] Estimation support
    - [ ] GNSS Measurements (This will likely be a dedicated separate project)
    - [ ] Radar range measurements
    - [ ] EKF
    - [ ] UKF
    - [ ] Particle filters
- [ ] Default Plotting
    - [ ] Ground Contact Geometry
    - [ ] Orbital Elements
    - [ ] 3D ECI / ECEF Trajectories
    - [ ] Relative Trajectories
